package com.forgeops.incidents.domain;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/**
 * Incident aggregate root (DOMAIN_MODEL.md §2/§10, PERSISTENCE_MODEL.md §8). An incident is the
 * authoritative record of a problem: it carries a lifecycle {@link IncidentState state}, a
 * {@link IncidentSeverity severity} (always present — INV-INC-004), its correlation context
 * (service + environment + failure signature), an optional current assignee, an optimistic-lock
 * {@code version} (INV-INC-005), and lifecycle timestamps.
 *
 * <p><strong>Scope (Phase 7 Slice 1 — persistence + aggregate foundation):</strong> this type
 * establishes the persisted shape and the foundation invariants only. It does <em>not</em>
 * implement lifecycle transitions, command authorization, optimistic-lock command behavior, or
 * assignment/comment/audit behavior — those belong to later slices. The {@code version} here is
 * a persisted value (starting at {@code 0} on creation); it is not yet mutated by commands.
 *
 * <p>Foundation invariants enforced by the constructor:
 * <ul>
 *   <li>{@code id}, {@code serviceId}, {@code environmentId}, {@code severity}, and
 *       {@code state} are required (a valid incident always has an identity, correlation
 *       context, severity, and state);</li>
 *   <li>{@code version} is non-negative;</li>
 *   <li>{@code createdAt} is required; {@code resolvedAt}/{@code closedAt} are optional;</li>
 *   <li>{@code currentAssigneeId} is optional (an incident may be unassigned).</li>
 * </ul>
 *
 * <p>Identity is stable/immutable (INV-INC-001) — the id is set once and never changes; the
 * aggregate exposes no id mutator. Incidents are never hard-deleted (PERSISTENCE_MODEL.md §19);
 * this type provides no deletion behavior. Ids follow the UUID v7 convention (ADR-0023) and are
 * generated by the caller via the shared {@code IdGenerator}, never inside this aggregate or in
 * persistence.
 *
 * <p>Framework-free by design (ADR-0030): no JPA, Spring, servlet, JSON, or RabbitMQ types.
 */
public final class Incident {

    private final UUID id;
    private final String title;
    private final UUID serviceId;
    private final UUID environmentId;
    private final String failureSignature;
    private final IncidentSeverity severity;
    private final IncidentState state;
    private final UUID currentAssigneeId;
    private final long version;
    private final Instant createdAt;
    private final Instant resolvedAt;
    private final Instant closedAt;

    /**
     * Full constructor, used both for creating a new incident and for rehydrating one from
     * persistence. Enforces the foundation invariants above.
     */
    public Incident(UUID id,
                    String title,
                    UUID serviceId,
                    UUID environmentId,
                    String failureSignature,
                    IncidentSeverity severity,
                    IncidentState state,
                    UUID currentAssigneeId,
                    long version,
                    Instant createdAt,
                    Instant resolvedAt,
                    Instant closedAt) {
        this.id = requireNonNull(id, "id");
        this.title = title;
        this.serviceId = requireNonNull(serviceId, "serviceId");
        this.environmentId = requireNonNull(environmentId, "environmentId");
        this.failureSignature = failureSignature;
        this.severity = requireNonNull(severity, "severity");
        this.state = requireNonNull(state, "state");
        this.currentAssigneeId = currentAssigneeId;
        if (version < 0) {
            throw new IllegalArgumentException("version must be non-negative");
        }
        this.version = version;
        this.createdAt = requireNonNull(createdAt, "createdAt");
        this.resolvedAt = resolvedAt;
        this.closedAt = closedAt;
    }

    /**
     * Factory for a freshly created incident: {@link IncidentState#OPEN}, {@code version = 0},
     * not yet resolved or closed. Used by both manual creation and (later) detection — a newly
     * created incident always starts OPEN (DOMAIN_MODEL.md §10). The id is supplied by the
     * caller (UUID v7 via the shared {@code IdGenerator}).
     */
    public static Incident open(UUID id,
                                String title,
                                UUID serviceId,
                                UUID environmentId,
                                String failureSignature,
                                IncidentSeverity severity,
                                UUID currentAssigneeId,
                                Instant createdAt) {
        return new Incident(id, title, serviceId, environmentId, failureSignature, severity,
                IncidentState.OPEN, currentAssigneeId, 0L, createdAt, null, null);
    }

    public UUID id() {
        return id;
    }

    public Optional<String> title() {
        return Optional.ofNullable(title);
    }

    public UUID serviceId() {
        return serviceId;
    }

    public UUID environmentId() {
        return environmentId;
    }

    public Optional<String> failureSignature() {
        return Optional.ofNullable(failureSignature);
    }

    public IncidentSeverity severity() {
        return severity;
    }

    public IncidentState state() {
        return state;
    }

    public Optional<UUID> currentAssigneeId() {
        return Optional.ofNullable(currentAssigneeId);
    }

    public long version() {
        return version;
    }

    public Instant createdAt() {
        return createdAt;
    }

    public Optional<Instant> resolvedAt() {
        return Optional.ofNullable(resolvedAt);
    }

    public Optional<Instant> closedAt() {
        return Optional.ofNullable(closedAt);
    }

    // --- Lifecycle commands (Phase 7 Slice 2) ----------------------------------------------
    // The aggregate owns the transition rules (DOMAIN_MODEL §10, INV-INC-002). Each command
    // validates the current state and returns a NEW Incident with the next state, the
    // documented timestamp side effects, and version + 1 (the intended next version — the
    // persistence layer enforces it with a conditional compare-and-set on the current version).
    // An illegal transition throws IllegalIncidentTransitionException (→ 409). Time is supplied
    // by the caller from the injected Clock (no Instant.now() in the domain).

    /** {@code OPEN → ACKNOWLEDGED}. */
    public Incident acknowledge(Instant now) {
        requireState(IncidentState.OPEN, "acknowledge");
        return withState(IncidentState.ACKNOWLEDGED, resolvedAt, closedAt);
    }

    /**
     * {@code OPEN|ACKNOWLEDGED → INVESTIGATING} (start), {@code MITIGATED → INVESTIGATING}
     * (regression), or {@code RESOLVED → INVESTIGATING} (reopen). The reopen/regression paths
     * preserve the existing {@code resolved_at}/{@code closed_at} — the docs do not specify
     * clearing them, so their values are left intact (a deliberate, reported decision).
     */
    public Incident investigate(Instant now) {
        if (state != IncidentState.OPEN && state != IncidentState.ACKNOWLEDGED
                && state != IncidentState.MITIGATED && state != IncidentState.RESOLVED) {
            throw new IllegalIncidentTransitionException(state, "investigate");
        }
        return withState(IncidentState.INVESTIGATING, resolvedAt, closedAt);
    }

    /** {@code INVESTIGATING → MITIGATED}. */
    public Incident mitigate(Instant now) {
        requireState(IncidentState.INVESTIGATING, "mitigate");
        return withState(IncidentState.MITIGATED, resolvedAt, closedAt);
    }

    /** {@code MITIGATED → RESOLVED}; sets {@code resolved_at}. */
    public Incident resolve(Instant now) {
        requireState(IncidentState.MITIGATED, "resolve");
        return withState(IncidentState.RESOLVED, now, closedAt);
    }

    /** {@code RESOLVED → CLOSED}; sets {@code closed_at}. Terminal state. */
    public Incident close(Instant now) {
        requireState(IncidentState.RESOLVED, "close");
        return withState(IncidentState.CLOSED, resolvedAt, now);
    }

    /**
     * Severity change (a separate command, not a lifecycle transition). Allowed in any
     * non-terminal state (not {@code CLOSED}). Severity is always present (INV-INC-004).
     */
    public Incident changeSeverity(IncidentSeverity newSeverity, Instant now) {
        requireNonNull(newSeverity, "severity");
        if (state == IncidentState.CLOSED) {
            throw new IllegalIncidentTransitionException(state, "change severity of");
        }
        return new Incident(id, title, serviceId, environmentId, failureSignature, newSeverity,
                state, currentAssigneeId, version + 1, createdAt, resolvedAt, closedAt);
    }

    private void requireState(IncidentState required, String command) {
        if (state != required) {
            throw new IllegalIncidentTransitionException(state, command);
        }
    }

    private Incident withState(IncidentState next, Instant newResolvedAt, Instant newClosedAt) {
        return new Incident(id, title, serviceId, environmentId, failureSignature, severity,
                next, currentAssigneeId, version + 1, createdAt, newResolvedAt, newClosedAt);
    }

    private static <T> T requireNonNull(T value, String field) {
        if (value == null) {
            throw new IllegalArgumentException(field + " is required");
        }
        return value;
    }
}
