package com.forgeops.incidents.domain;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/**
 * Incident aggregate root (DOMAIN_MODEL.md §2/§10, PERSISTENCE_MODEL.md §8). An incident is the
 * authoritative record of a problem: it carries a lifecycle {@link IncidentState state}, a
 * {@link IncidentSeverity severity} (always present — INV-INC-004), its correlation context
 * (service + environment + failure signature), an optional current assignee, an optimistic-lock
 * {@code version} (INV-INC-005), and lifecycle timestamps.
 *
 * <p><strong>Scope (Phase 7 Slice 1 — persistence + aggregate foundation):</strong> this type
 * establishes the persisted shape and the foundation invariants only. It does <em>not</em>
 * implement lifecycle transitions, command authorization, optimistic-lock command behavior, or
 * assignment/comment/audit behavior — those belong to later slices. The {@code version} here is
 * a persisted value (starting at {@code 0} on creation); it is not yet mutated by commands.
 *
 * <p>Foundation invariants enforced by the constructor:
 * <ul>
 *   <li>{@code id}, {@code serviceId}, {@code environmentId}, {@code severity}, and
 *       {@code state} are required (a valid incident always has an identity, correlation
 *       context, severity, and state);</li>
 *   <li>{@code version} is non-negative;</li>
 *   <li>{@code createdAt} is required; {@code resolvedAt}/{@code closedAt} are optional;</li>
 *   <li>{@code currentAssigneeId} is optional (an incident may be unassigned).</li>
 * </ul>
 *
 * <p>Identity is stable/immutable (INV-INC-001) — the id is set once and never changes; the
 * aggregate exposes no id mutator. Incidents are never hard-deleted (PERSISTENCE_MODEL.md §19);
 * this type provides no deletion behavior. Ids follow the UUID v7 convention (ADR-0023) and are
 * generated by the caller via the shared {@code IdGenerator}, never inside this aggregate or in
 * persistence.
 *
 * <p>Framework-free by design (ADR-0030): no JPA, Spring, servlet, JSON, or RabbitMQ types.
 */
public final class Incident {

    private final UUID id;
    private final String title;
    private final UUID serviceId;
    private final UUID environmentId;
    private final String failureSignature;
    private final IncidentSeverity severity;
    private final IncidentState state;
    private final UUID currentAssigneeId;
    private final long version;
    private final Instant createdAt;
    private final Instant resolvedAt;
    private final Instant closedAt;

    /**
     * Full constructor, used both for creating a new incident and for rehydrating one from
     * persistence. Enforces the foundation invariants above.
     */
    public Incident(UUID id,
                    String title,
                    UUID serviceId,
                    UUID environmentId,
                    String failureSignature,
                    IncidentSeverity severity,
                    IncidentState state,
                    UUID currentAssigneeId,
                    long version,
                    Instant createdAt,
                    Instant resolvedAt,
                    Instant closedAt) {
        this.id = requireNonNull(id, "id");
        this.title = title;
        this.serviceId = requireNonNull(serviceId, "serviceId");
        this.environmentId = requireNonNull(environmentId, "environmentId");
        this.failureSignature = failureSignature;
        this.severity = requireNonNull(severity, "severity");
        this.state = requireNonNull(state, "state");
        this.currentAssigneeId = currentAssigneeId;
        if (version < 0) {
            throw new IllegalArgumentException("version must be non-negative");
        }
        this.version = version;
        this.createdAt = requireNonNull(createdAt, "createdAt");
        this.resolvedAt = resolvedAt;
        this.closedAt = closedAt;
    }

    /**
     * Factory for a freshly created incident: {@link IncidentState#OPEN}, {@code version = 0},
     * not yet resolved or closed. Used by both manual creation and (later) detection — a newly
     * created incident always starts OPEN (DOMAIN_MODEL.md §10). The id is supplied by the
     * caller (UUID v7 via the shared {@code IdGenerator}).
     */
    public static Incident open(UUID id,
                                String title,
                                UUID serviceId,
                                UUID environmentId,
                                String failureSignature,
                                IncidentSeverity severity,
                                UUID currentAssigneeId,
                                Instant createdAt) {
        return new Incident(id, title, serviceId, environmentId, failureSignature, severity,
                IncidentState.OPEN, currentAssigneeId, 0L, createdAt, null, null);
    }

    public UUID id() {
        return id;
    }

    public Optional<String> title() {
        return Optional.ofNullable(title);
    }

    public UUID serviceId() {
        return serviceId;
    }

    public UUID environmentId() {
        return environmentId;
    }

    public Optional<String> failureSignature() {
        return Optional.ofNullable(failureSignature);
    }

    public IncidentSeverity severity() {
        return severity;
    }

    public IncidentState state() {
        return state;
    }

    public Optional<UUID> currentAssigneeId() {
        return Optional.ofNullable(currentAssigneeId);
    }

    public long version() {
        return version;
    }

    public Instant createdAt() {
        return createdAt;
    }

    public Optional<Instant> resolvedAt() {
        return Optional.ofNullable(resolvedAt);
    }

    public Optional<Instant> closedAt() {
        return Optional.ofNullable(closedAt);
    }

    private static <T> T requireNonNull(T value, String field) {
        if (value == null) {
            throw new IllegalArgumentException(field + " is required");
        }
        return value;
    }
}
